name: Acceptance tests

on: pull_request

env:
  BUNDLE_PATH: vendor/bundle
  BUNDLE_WITHOUT: development:test
  BUNDLE_JOBS: 4
  BUNDLE_RETRY: 3

jobs:
  setup_matrix:
    name: 'Setup Test Matrix'
    runs-on: ubuntu-latest
    outputs:
      setfiles: ${{ steps.get-setfiles.outputs.setfiles }}
      puppet_major_versions: ${{ steps.get-setfiles.outputs.puppet_major_versions }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.7"
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-2.7-gems-acceptance-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-2.7-gems-acceptance-
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
          bundle clean
      - name: Setup Acceptance Test Matrix
        id: get-setfiles
        run: bundle exec metadata2gha-beaker --use-fqdn --pidfile-workaround false

  acceptance:
    needs: setup_matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        setfile: ${{fromJson(needs.setup_matrix.outputs.setfiles)}}
        puppet: ${{fromJson(needs.setup_matrix.outputs.puppet_major_versions)}}
    name: Puppet ${{ matrix.puppet }} - ${{ matrix.setfile.name }}
    steps:
      - name: Enable IPv6 on docker
        run: |
          echo '{"ipv6":true,"fixed-cidr-v6":"2001:db8:1::/64"}' | sudo tee /etc/docker/daemon.json
          sudo service docker restart
      - uses: actions/checkout@v2
      - name: Setup ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.7"
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-2.7-gems-acceptance-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-2.7-gems-acceptance-
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Run tests
        run: bundle exec rake beaker
        env:
          BEAKER_PUPPET_COLLECTION: puppet${{ matrix.puppet }}
          BEAKER_setfile: ${{ matrix.setfile.value }}
